language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

script: npm run test-ci

addons:
  sauce_connect:
    username: ampersandjs-ci
    access_key:
      secure: "qZGwdyj62108JOiUMZjgLGCQ8k9G/Z3HDhqzxaMmFC0PgxYX6Z0IglTeYdTUWhalIzjM/WplW2iV3i0hfM8ufvLh1XVHZfFb0ZUtAi7i8fmJMHUflQ3/8E3rJGsLRn06Z+mW1nJB2aC2BgqCKlu4qhYKfTAH1/wr4sd8ZMG87vg="
